haphpy_index:
    locales:
        en: "/en/"
        fr: "/fr/"
        es: "/es/"
    defaults: { _controller: AppBundle:Default:index }

haphpy_contribution_user:
    locales:
        en: "/en/contribution/{authProvider}/{identifier}"
        fr: "/fr/contribution/{authProvider}/{identifier}"
        es: "/es/contribucion/{authProvider}/{identifier}"
    defaults: { _controller: AppBundle:Default:contribution }
    requirements:
        authProvider:  "g|f|t"

haphpy_about:
    locales:
        en: "/en/about"
        fr: "/fr/a-propos"
        es: "/es/acerca-de"
    defaults: { _controller: AppBundle:Default:about }
